server:
  port: 8080

spring:
  application:
    name: user-service
  cloud:
    config:
      uri: ${SPRING_CLOUD_CONFIG_URI:http://localhost:8888}
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:default}
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${JWT_ISSUER_URI:smucode-auth-service}
          jwk-set-uri: ${JWT_JWK_SET_URI:http://localhost:8000/api/auth/.well-known/jwks.json}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

logging:
  level:
    root: INFO
    com.cs203.smucode: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

eureka:
  client:
    enabled: true
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

aws:
  bucket:
    name: ${AWS_ASSETS_BUCKET:brawlcode-assets}
