server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://smucode-user-db.ct2ummoyigfv.ap-southeast-1.rds.amazonaws.com
    driverClassName: org.postgresql.Driver
    username: postgres
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true

logging:
  level:
    com.cs203.smucode: DEBUG

eureka:
  client:
    enabled: false

jwt:
  expiration: 600000

aws:
  region: ap-southeast-1
  secretsmanager:
    db:
      secret: rds!db-58dd6661-9e9d-4ce5-92da-65b895d6a92a
  rds:
    db:
      identifier: smucode-user-db