name: Build image and push to ECR

on: # workflow trigger on manual, PR & push to dev
  push:
    branches: [dev, main]
  workflow_dispatch:

permissions:
  id-token: write # for aws oidc connection
  contents: read # to check out code

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Pull code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Set environment variables
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "SPRING_PROFILE=prod" >> $GITHUB_ENV
            echo "DOCKER_TAG=prod" >> $GITHUB_ENV
          else
            echo "SPRING_PROFILE=local" >> $GITHUB_ENV
            echo "DOCKER_TAG=dev" >> $GITHUB_ENV
          fi

      - name: Build with Maven
        run: mvn clean package -Dspring.profiles.active=${{ env.SPRING_PROFILE }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          IMAGE_TAG: ${{ env.DOCKER_TAG }}-${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .

          docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:${{ env.DOCKER_TAG }}

          docker push --all-tags $ECR_REGISTRY/$ECR_REPOSITORY
